name: mergen

# # Stable diffusion service base
# x-base_service: &base_service
#     container_name: mergen-sd-webui-api-container
#     ports:
#       - "${SD_API_PORT}:${SD_API_PORT}"
#     hostname: ${SD_API_HOST}
#     volumes:
#       - &v1 ./sd-webui-api/data:/data
#       - &v2 ./sd-webui-api/output:/output
#     env_file:
#       - .env
#     stop_signal: SIGKILL
#     tty: true
#     deploy:
#       resources:
#         reservations:
#           devices:
#               - driver: nvidia
#                 device_ids: ['0']
#                 capabilities: [compute, utility]

services:
# # Stable diffusion service
#   sd-webui-api: &automatic
#     <<: *base_service
#     profiles: ["gateway_sd"]
#     build: ./sd-webui-api/services/AUTOMATIC1111
#     image: mergen-sd-webui-api-image
#     environment:
#       - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
#     networks:
#       - mergen-network
#   download:
#     build: ./sd-webui-api/services/download/
#     profiles: ["download"]
#     volumes:
#       - *v1
# API gateway
  server:
    profiles: ["gateway_sd"]
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: mergen-server-image
    container_name: mergen-server-container
    env_file:
      - .env
    volumes:
      - ./server:/app
      - ../Frontend/Assets/Material:/app/Material 
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - mergen-network

# llama-stack-server
  llama-stack-server:
    image: llamastack/distribution-together  # 使用 Together 版本的 Llama Stack
    container_name: llama-stack-together-container
    env_file:
      - .env
    ports:
      - "${LLAMA_STACK_PORT}:${LLAMA_STACK_PORT}"
    environment:
      - LLAMA_STACK_PORT=${LLAMA_STACK_PORT}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}  # 从 .env 读取 API Key
    networks:
      - mergen-network
    restart: always  # 让容器在崩溃时自动重启
    # command: ["--port", "5001"]


  ngrok:
      image: ngrok/ngrok:latest
      container_name: ngrok_tunnel
      env_file:
      - .env
      command: ["http", "server:8000"]  # ✅ 把 `server` 服务暴露到公网
      ports:
        - "4040:4040"  # ✅ 访问 `ngrok` Web 界面，查看公网 URL
      environment:
        - NGROK_AUTHTOKEN=${NGROK_API_KEY}  # ✅ 你的 ngrok 认证 token（从 ngrok 官网获取）
      networks:
      - mergen-network

# interior-design-assistant
  ida-llama-agent:
    build:
      context: ./ida-llama-agent
      dockerfile: Dockerfile
    image: mergen-ida-llama-agent
    container_name: mergen-ida-llama-agent-container
    env_file:
      - .env
    ports:
      - "${IDA_AGENT_PORT}:${IDA_AGENT_PORT}"
    networks:
      - mergen-network
    depends_on:
      - llama-stack-server

# network
networks:
  mergen-network:
    driver: bridge
